### ISSUE TITLE
time_dataset.py error

### ISSUE THREAD

**Issue by LucySha** [huyanxin/phasen#2]
line 100:duration=item['duration']报错KeyError
查看了一下，target_list,没有‘duration’这一项，应该是数据处理那部分出错，但是用代码中的lst仍然报错，请问是哪一步出了错？

**Comment by huyanxin** [comment]
Sorry，I forgot to add something  in ReadMe.

**Comment by huyanxin** [comment]
You can do this to add duration information in tr.lst or cv.lst
`python /tools/add_duration.py xxxx.lst`
Sorry, I forgot adding it in ReadMe, and I will add it soon.

抱歉，我忘记在Readme里加这部分了，这个duration信息其实就是时长信息，在tr.lst和cv.lst加入duration后就可以在语音切片时能够预先拿到时长信息来切片；而语音切片的操作是因为语音长度不一，所以就把一个batch内语音切成等长的（padding策略亦可，但是速度会慢一些）。

**Comment by LucySha** [comment]
@huyanxin 非常感谢，将duration加进去之后，代码可以运行起来。
还有几个问题想请教您:
1.time_dataset.py line 44行中，产生的lst每一个item包含干净和带噪音频的路径，分别对应inputs和labels吗？这个labels能用到哪些地方？
2. PHASEN的实测效果怎样？能否提供pretrained model,我之前对比了wavenet，segan以及deepfeatureloss，训练后模型进行实测与数据集的结果还是有差距的。

**Comment by huyanxin** [comment]
1. 是这样，inputs就是带噪语音noisy-wav，labels就是clean-wav或者说是reference，给网络用来计算loss的，你看我代码https://github.com/huyanxin/phasen/blob/31ee2f1ba89b535142a5189abf913e9ac7f36404/steps/run_phasen.py#L74，在这里计算了Power Compress loss；
2. 目前看的话，我这边训练的无论是Phasen还是其他模型，在实际样例上都还有能接受的效果吧，当然和训练集越匹配效果越好，Readme中的语谱图就是从实录样例中导出的，你想要模型的话把邮箱给我吧，我发你一个。

**Comment by LucySha** [comment]
@huyanxin 邮箱1909592778@qq.com 感谢您的分享。我之前把模型用到实测环境时，总体降噪效果是可以接受的，但是会遇到比较明显的两个问题：1. 语音失真，表现在中文发音降噪后会出现断音的情况，2.用librispeech训练后的模型有的降噪后的音频会有明显的底噪，类似白噪声。请问您之前有碰到过类似的问题吗？处理过程中应该怎样尽可能避免呢？

**Comment by huyanxin** [comment]
OK，已发
